Lsascha:
  FullCalendar:
    # module widget setup
    moduleConfiguration:
      widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
      
    # Calendar plugin configuration
    googleCalendarApiKey: ~
    language: 'all'

    # settings for the standalone calendar view. ( by default at http://yourdomain.com/calendar.html )
    standaloneCalendar:
      # default view can be 'month', 'agendaWeek', 'agendaDay', 'basicWeek' or 'basicDay'
      defaultView: 'month'
      nowIndicator: TRUE
      # see http://fullcalendar.io/docs/display/header/ for more info
      header:
        left: 'prev,next today'
        center: 'prevYear title nextYear'
        right: 'month,agendaWeek,agendaDay'



# Backend modules configuration
TYPO3:
  Neos:

    typoScript:
      autoInclude:
        'Lsascha.FullCalendar': TRUE

    modules:
      calendarAdministration:
        label: 'Calendar Administration'
        controller: '\Lsascha\FullCalendar\Controller\Module\CalendarAdministrationController'
        description: 'administrate calendars'
        icon: 'icon-calendar'
        privilegeTarget: 'Lsascha.FullCalendar:AdministrationCalendarManagementControllerActions'
        submodules:
          lsaschaCalendarManagement:
            label: 'Calendar Management'
            icon: 'icon-calendar'
            controller: '\Lsascha\FullCalendar\Controller\Module\Administration\CalendarManagementController'
            description: 'Provides administration tools for maintaining calendars.'
            privilegeTarget: 'Lsascha.FullCalendar:AdministrationCalendarManagementControllerActions'