Lsascha:
  FullCalendar:
    # module widget setup
    moduleConfiguration:
      widgetTemplatePathAndFileName: 'resource://Neos.Neos/Private/Templates/Module/Widget.html'
      
    # Calendar plugin configuration
    googleCalendarApiKey: ~
    language: 'all'

    # settings for the standalone calendar view. ( by default at http://yourdomain.com/calendar.html )
    standaloneCalendar:
      # set to Object Identifiers that should be used as event sources. for example: ['aa-bb-cc-dd-ee', 'ff-gg-hh-ii-jj']
      eventSources: ~
      # default view can be 'month', 'agendaWeek', 'agendaDay', 'basicWeek' or 'basicDay'
      defaultView: 'month'
      nowIndicator: TRUE
      # see http://fullcalendar.io/docs/display/header/ for more info
      header:
        left: 'prev,next today'
        center: 'prevYear title nextYear'
        right: 'month,agendaWeek,agendaDay'



# Backend modules configuration
Neos:
  Neos:

    mvc:
      routes:
        'Lsascha.FullCalendar': TRUE

    fusion:
      autoInclude:
        'Lsascha.FullCalendar': TRUE

    modules:
      management:
        submodules:
          calendarAdministration:
            label: 'Calendar'
            icon: 'icon-calendar'
            mainStylesheet: 'Lite'
            controller: '\Lsascha\FullCalendar\Controller\Module\Administration\CalendarManagementController'
            description: 'Provides administration tools for maintaining calendars.'
            privilegeTarget: 'Lsascha.FullCalendar:AdministrationCalendarManagementControllerActions'
